name: OpenSSF Scorecard

on:
  push:
    branches:
      - main
  schedule:
    - cron: "41 4 * * 1"
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  scorecard:
    name: Scorecard
    runs-on: ubuntu-24.04
    if: github.repository == 'stackradar/stackradar-cli'
    permissions:
      contents: read
      id-token: write
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Run Scorecard
        uses: ossf/scorecard-action@2d1146689b8cda280b9bc96326124645441f03bc # v2.4.4
        with:
          results_file: scorecard.sarif
          results_format: sarif
          publish_results: true
        env:
          GITHUB_AUTH_TOKEN: ${{ github.token }}

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@5595ccaf912efad79be6eef63a5619ff05969be3 # v4
        with:
          sarif_file: scorecard.sarif
